version: '2'
services:
#  for application container
  web:
    build: .
    image: wastings:1.0.0
    ports:
      - 8080:8080
    depends_on:
      - db
#    for database docker container
  db:
    container_name: postgresCont
    image: postgres:latest
    volumes:
      - postgresCont:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=money
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

volumes:
  postgresCont: {}